package com.billy.UniQuery.mapper;

import com.billy.UniQuery.entity.Answer;
import java.util.List;

public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int deleteByPrimaryKey(Integer answerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    Answer selectByPrimaryKey(Integer answerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    List<Answer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int updateByPrimaryKey(Answer record);
}