package com.billy.UniQuery.mapper;

import com.billy.UniQuery.entity.Cate;
import java.util.List;

public interface CateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int deleteByPrimaryKey(Integer cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int insert(Cate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    Cate selectByPrimaryKey(Integer cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    List<Cate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int updateByPrimaryKey(Cate record);
}