package com.billy.UniQuery.mapper;

import com.billy.UniQuery.entity.Followers;
import java.util.List;

public interface FollowersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_followers
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_followers
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int insert(Followers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_followers
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    Followers selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_followers
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    List<Followers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_followers
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int updateByPrimaryKey(Followers record);
}