package com.billy.UniQuery.mapper;

import com.billy.UniQuery.entity.Notice;
import java.util.List;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int deleteByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    Notice selectByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    List<Notice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int updateByPrimaryKey(Notice record);
}