package com.billy.UniQuery.mapper;

import com.billy.UniQuery.entity.Pm;
import java.util.List;

public interface PmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int deleteByPrimaryKey(Integer pmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int insert(Pm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    Pm selectByPrimaryKey(Integer pmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    List<Pm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    int updateByPrimaryKey(Pm record);
}