package com.billy.UniQuery.entity;

public class Followers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_followers.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_followers.following
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer following;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followers.userid
     *
     * @return the value of t_followers.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followers.userid
     *
     * @param userid the value for t_followers.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_followers.following
     *
     * @return the value of t_followers.following
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getFollowing() {
        return following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_followers.following
     *
     * @param following the value for t_followers.following
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setFollowing(Integer following) {
        this.following = following;
    }
}