package com.billy.UniQuery.entity;

import java.util.Date;

public class Pm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm.pmid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer pmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm.content
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm.recieverid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer recieverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm.createdate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm.isread
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private String isread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm.pmid
     *
     * @return the value of t_pm.pmid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getPmid() {
        return pmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm.pmid
     *
     * @param pmid the value for t_pm.pmid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setPmid(Integer pmid) {
        this.pmid = pmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm.content
     *
     * @return the value of t_pm.content
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm.content
     *
     * @param content the value for t_pm.content
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm.userid
     *
     * @return the value of t_pm.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm.userid
     *
     * @param userid the value for t_pm.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm.recieverid
     *
     * @return the value of t_pm.recieverid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getRecieverid() {
        return recieverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm.recieverid
     *
     * @param recieverid the value for t_pm.recieverid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setRecieverid(Integer recieverid) {
        this.recieverid = recieverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm.createdate
     *
     * @return the value of t_pm.createdate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm.createdate
     *
     * @param createdate the value for t_pm.createdate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm.isread
     *
     * @return the value of t_pm.isread
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public String getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm.isread
     *
     * @param isread the value for t_pm.isread
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setIsread(String isread) {
        this.isread = isread == null ? null : isread.trim();
    }
}