package com.billy.UniQuery.entity;

import java.util.Date;

public class Report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.reportid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer reportid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.reportContent
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private String reportcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.questionid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.status
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.answerid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer answerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.createDate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.commentid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    private Integer commentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.reportid
     *
     * @return the value of t_report.reportid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getReportid() {
        return reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.reportid
     *
     * @param reportid the value for t_report.reportid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setReportid(Integer reportid) {
        this.reportid = reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.reportContent
     *
     * @return the value of t_report.reportContent
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public String getReportcontent() {
        return reportcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.reportContent
     *
     * @param reportcontent the value for t_report.reportContent
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setReportcontent(String reportcontent) {
        this.reportcontent = reportcontent == null ? null : reportcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.questionid
     *
     * @return the value of t_report.questionid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.questionid
     *
     * @param questionid the value for t_report.questionid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.userid
     *
     * @return the value of t_report.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.userid
     *
     * @param userid the value for t_report.userid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.status
     *
     * @return the value of t_report.status
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.status
     *
     * @param status the value for t_report.status
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.answerid
     *
     * @return the value of t_report.answerid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.answerid
     *
     * @param answerid the value for t_report.answerid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setAnswerid(Integer answerid) {
        this.answerid = answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.createDate
     *
     * @return the value of t_report.createDate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.createDate
     *
     * @param createdate the value for t_report.createDate
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.commentid
     *
     * @return the value of t_report.commentid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.commentid
     *
     * @param commentid the value for t_report.commentid
     *
     * @mbg.generated Fri Apr 10 10:37:15 CST 2020
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }
}